from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

from .catalog import App, get_app, load_catalog, search_apps, validate_catalog
from .render import render_html, render_json, render_markdown


def _add_json_flag(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--json", action="store_true", help="print machine-readable JSON")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="openapps",
        description="Discover and compare open-source software you can run yourself.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    list_parser = subparsers.add_parser("list", help="list catalog entries")
    list_parser.add_argument("--category", help="filter by category")
    _add_json_flag(list_parser)

    search_parser = subparsers.add_parser("search", help="search catalog entries")
    search_parser.add_argument("query")
    _add_json_flag(search_parser)

    show_parser = subparsers.add_parser("show", help="show one catalog entry")
    show_parser.add_argument("slug")
    show_parser.add_argument("--json", action="store_true")

    doctor_parser = subparsers.add_parser("doctor", help="validate bundled catalog")
    doctor_parser.add_argument("--json", action="store_true")

    render_parser = subparsers.add_parser("render", help="render the catalog")
    render_parser.add_argument("--format", choices=("html", "json", "markdown"), default="html")
    render_parser.add_argument("--output", type=Path)

    export_parser = subparsers.add_parser("export", help="export a reusable app brief")
    export_parser.add_argument("slug")
    export_parser.add_argument("--output", type=Path, required=True)

    return parser


def _write_or_print(content: str, output: Path | None) -> None:
    if output is None:
        print(content, end="" if content.endswith("\n") else "\n")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")


def _app_rows(apps: Sequence[App]) -> str:
    return "\n".join(
        f"{app.slug:28} {app.category:18} {app.name} - {app.summary}" for app in apps
    )


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    apps = load_catalog()

    if args.command == "list":
        selected = tuple(
            app for app in apps if not args.category or app.category.casefold() == args.category.casefold()
        )
        if args.json:
            print(render_json(selected), end="")
        else:
            print(_app_rows(selected))
        return 0

    if args.command == "search":
        results = search_apps(apps, args.query)
        if args.json:
            print(render_json(results), end="")
        else:
            print(_app_rows(results))
        return 0

    if args.command == "show":
        try:
            app = get_app(apps, args.slug)
        except KeyError:
            print(f"Unknown app: {args.slug}")
            return 2
        if args.json:
            print(render_json((app,)), end="")
        else:
            print(render_markdown(app), end="")
        return 0

    if args.command == "doctor":
        errors = validate_catalog(apps)
        if args.json:
            import json

            print(json.dumps({"valid": not errors, "errors": errors}, indent=2))
        elif errors:
            print("Catalog invalid:")
            print("\n".join(f"- {error}" for error in errors))
        else:
            print(f"Catalog valid: {len(apps)} apps")
        return 0 if not errors else 1

    if args.command == "render":
        if args.format == "html":
            content = render_html(apps)
        elif args.format == "json":
            content = render_json(apps)
        else:
            content = "\n\n".join(render_markdown(app) for app in apps) + "\n"
        _write_or_print(content, args.output)
        return 0

    if args.command == "export":
        try:
            app = get_app(apps, args.slug)
        except KeyError:
            print(f"Unknown app: {args.slug}")
            return 2
        args.output.mkdir(parents=True, exist_ok=True)
        (args.output / "README.md").write_text(
            render_markdown(app)
            + "\n\n> Generated by OpenApps. Verify upstream installation and security guidance before deployment.\n",
            encoding="utf-8",
        )
        (args.output / "app.json").write_text(render_json((app,)), encoding="utf-8")
        print(f"Exported {app.slug} to {args.output}")
        return 0

    print("Unknown command", file=sys.stderr)
    return 2
