"""Record the real OpenApps CLI smoke test as a shareable GIF.

Requires Pillow only when regenerating demo assets. The commands themselves
run through the local package so the transcript reflects the current checkout.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
COMMANDS = (
    ("replace notion", ("replace", "notion")),
    ("plan rustdesk", ("plan", "rustdesk", "--platform", "all")),
    ("share rustdesk", ("share", "rustdesk")),
    (
        "render storefront",
        ("render", "--format", "html", "--output", "docs/index.html"),
    ),
)


def _font(size: int) -> ImageFont.ImageFont:
    for candidate in (
        Path(r"C:\Windows\Fonts\CascadiaMono.ttf"),
        Path(r"C:\Windows\Fonts\CascadiaCode.ttf"),
        Path(r"C:\Windows\Fonts\consola.ttf"),
    ):
        if candidate.exists():
            return ImageFont.truetype(str(candidate), size)
    return ImageFont.load_default()


def _run(args: tuple[str, ...]) -> tuple[str, int]:
    completed = subprocess.run(
        [sys.executable, "-m", "openapps", *args],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    return completed.stdout.rstrip(), completed.returncode


def _frame(label: str, command: str, output: str, return_code: int) -> Image.Image:
    image = Image.new("RGB", (1400, 800), "#0b1020")
    draw = ImageDraw.Draw(image)
    title_font = _font(24)
    body_font = _font(21)
    small_font = _font(18)

    draw.rounded_rectangle((34, 30, 1366, 770), radius=24, fill="#111827", outline="#334155", width=2)
    draw.rounded_rectangle((34, 30, 1366, 96), radius=24, fill="#172033")
    draw.rectangle((34, 70, 1366, 96), fill="#172033")
    for x, color in ((68, "#fb7185"), (98, "#fbbf24"), (128, "#34d399")):
        draw.ellipse((x - 8, 55, x + 8, 71), fill=color)
    draw.text((170, 48), "OPENAPPS / REAL SMOKE TEST", font=title_font, fill="#e2e8f0")
    draw.text((1160, 52), label.upper(), font=small_font, fill="#67e8f9")

    y = 132
    draw.text((72, y), f"$ {command}", font=body_font, fill="#86efac")
    y += 46
    wrapped: list[str] = []
    for line in output.splitlines() or ["(no output)"]:
        wrapped.extend(textwrap.wrap(line, width=112) or [""])
    max_lines = 25
    if len(wrapped) > max_lines:
        wrapped = wrapped[: max_lines - 1] + ["... see the full transcript in assets/"]
    for line in wrapped:
        draw.text((72, y), line, font=body_font, fill="#cbd5e1")
        y += 25
    status_color = "#86efac" if return_code == 0 else "#fb7185"
    draw.text((72, 724), f"exit code: {return_code}", font=small_font, fill=status_color)
    return image


def record(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    frames: list[Image.Image] = []
    durations: list[int] = []
    transcript: list[str] = [
        "OpenApps real CLI smoke test",
        "Generated by scripts/record_demo.py",
        "",
    ]

    for label, args in COMMANDS:
        command = "python -m openapps " + " ".join(args)
        output, return_code = _run(args)
        transcript.extend((f"$ {command}", output, f"[exit code: {return_code}]", ""))
        frames.append(_frame(label, command, output, return_code))
        durations.append(2800)
        if return_code != 0:
            raise RuntimeError(f"Smoke test failed for {command} with exit code {return_code}")

    gif_path = output_dir / "openapps-demo.gif"
    frames[0].save(
        gif_path,
        save_all=True,
        append_images=frames[1:],
        duration=durations,
        loop=0,
        optimize=False,
    )
    transcript_path = output_dir / "openapps-demo-transcript.txt"
    transcript_path.write_text("\n".join(transcript).rstrip() + "\n", encoding="utf-8")
    return gif_path, transcript_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("assets"),
        help="Directory for the GIF and transcript (relative to the repository root).",
    )
    arguments = parser.parse_args()
    output_dir = arguments.output_dir
    if not output_dir.is_absolute():
        output_dir = ROOT / output_dir
    gif_path, transcript_path = record(output_dir)
    print(f"Recorded {gif_path.relative_to(ROOT)}")
    print(f"Transcript {transcript_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
